apiVersion: v1
kind: Pod
metadata:
  name: yl-glad-annotate
spec:
  restartPolicy: Never
  volumes:
    - name: sfr-home-pv-yang-li
      persistentVolumeClaim:
        claimName: sfr-home-pvc-yang-li
    - name: embeddings-volume
      emptyDir: {}
  containers:
    - name: glad
      image: "gcr.io/salesforce-research-internal/vzhong-glad:latest"
      command: ["/bin/bash", "-c", "cd /opt/glad && mkdir -p /export/yl/glad/data && ln -s /export/yl/glad/data/ /opt/glad/data && python -u preprocess_data.py"]
      resources:
        requests:
          memory: "32000Mi"
      volumeMounts:
        - name: sfr-home-pv-yang-li
          mountPath: "/export"
        - name: embeddings-volume
          mountPath: /embeddings
      env:
        - name: EMBEDDINGS_ROOT
          value: "/embeddings/embeddings"
    - name: corenlp
      image: "vzhong/corenlp-server"
  initContainers:
    - name: embeddings
      image: "vzhong/embeddings:0.0.5"
      command: ["cp", "-r", "/opt/embeddings/", "/embeddings"]
      volumeMounts:
        - mountPath: /embeddings
          name: embeddings-volume